// Api Keys
const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

// AI Models
const GEMINI_FLASH_MODEL = process.env.GEMINI_FLASH_MODEL;
const GEMINI_PRO_MODEL = process.env.GEMINI_PRO_MODEL;
const GEMINI_IMAGE_EDIT_MODEL = process.env.GEMINI_IMAGE_EDIT_MODEL;
const OPENAI_MODEL = process.env.OPENAI_MODEL;
const IMAGEN_3_MODEL = process.env.IMAGEN_3_MODEL;
const IMAGEN_4_STANDARD_MODEL = process.env.IMAGEN_4_STANDARD_MODEL;
const IMAGEN_4_ULTRA_MODEL = process.env.IMAGEN_4_ULTRA_MODEL;
const VEO_MODEL = process.env.VEO_MODEL;

// Discord Bot Credentials
const GUILD_ID = process.env.GUILD_ID;
const DISCORD_BOT_CLIENT_ID = process.env.DISCORD_BOT_CLIENT_ID;
const DISCORD_BOT_TOKEN = process.env.DISCORD_BOT_TOKEN;

export {
  OPENAI_API_KEY,
  GEMINI_API_KEY,
  GEMINI_FLASH_MODEL,
  GEMINI_PRO_MODEL,
  GEMINI_IMAGE_EDIT_MODEL,
  OPENAI_MODEL,
  IMAGEN_3_MODEL,
  IMAGEN_4_STANDARD_MODEL,
  IMAGEN_4_ULTRA_MODEL,
  VEO_MODEL,
  GUILD_ID,
  DISCORD_BOT_CLIENT_ID,
  DISCORD_BOT_TOKEN,
};
