// Api Keys
const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

// AI Models
const GEMINI_FLASH_MODEL = process.env.GEMINI_FLASH_MODEL;
const GEMINI_PRO_MODEL = process.env.GEMINI_PRO_MODEL;
const OPENAI_MODEL = process.env.OPENAI_MODEL;

// Discord Bot Credentials
const GUILD_ID = process.env.GUILD_ID;
const DISCORD_BOT_CLIENT_ID = process.env.DISCORD_BOT_CLIENT_ID;
const DISCORD_BOT_TOKEN = process.env.DISCORD_BOT_TOKEN;

export {
  OPENAI_API_KEY,
  GEMINI_API_KEY,
  GEMINI_FLASH_MODEL,
  GEMINI_PRO_MODEL,
  OPENAI_MODEL,
  GUILD_ID,
  DISCORD_BOT_CLIENT_ID,
  DISCORD_BOT_TOKEN,
};
